/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio4;

import java.util.TreeSet;

/**
 *
 * @author User
 */
public class DeTodoSA extends javax.swing.JFrame {
 public static TreeSet<Producto> listaProductos = new TreeSet<Producto>();

    /**
     * Creates new form DeTodoSA
     */
    public DeTodoSA() {
        initComponents();
        cargarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiGestorProducto = new javax.swing.JMenuItem();
        jmbConsultas = new javax.swing.JMenu();
        jmiBuscarRubro = new javax.swing.JMenuItem();
        jmiBuscarNombre = new javax.swing.JMenuItem();
        jmiBuscarPrecio = new javax.swing.JMenuItem();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );

        jMenu1.setText("Administracion");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jmiGestorProducto.setText("Productos");
        jmiGestorProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestorProductoActionPerformed(evt);
            }
        });
        jMenu1.add(jmiGestorProducto);

        jMenuBar1.add(jMenu1);

        jmbConsultas.setText("Consultas");

        jmiBuscarRubro.setText("Por rubro...");
        jmiBuscarRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBuscarRubroActionPerformed(evt);
            }
        });
        jmbConsultas.add(jmiBuscarRubro);

        jmiBuscarNombre.setText("Por nombre...");
        jmiBuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBuscarNombreActionPerformed(evt);
            }
        });
        jmbConsultas.add(jmiBuscarNombre);

        jmiBuscarPrecio.setText("Por precio...");
        jmiBuscarPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBuscarPrecioActionPerformed(evt);
            }
        });
        jmbConsultas.add(jmiBuscarPrecio);

        jMenuBar1.add(jmbConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiGestorProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestorProductoActionPerformed
         //Ventana de Gestion de Producto
        escritorio.removeAll();
        escritorio.repaint();
        GestorDeProducto gest = new GestorDeProducto();
        gest.setVisible(true);
        escritorio.add(gest);
        escritorio.moveToFront(gest);
    }//GEN-LAST:event_jmiGestorProductoActionPerformed

    private void jmiBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBuscarNombreActionPerformed
        // Ventana de busqueda por nombre de producto
        escritorio.removeAll();
        escritorio.repaint();
        BusquedaPorNombre bpn = new BusquedaPorNombre();
        bpn.setVisible(true);
        escritorio.add(bpn);
        escritorio.moveToFront(bpn);
    }//GEN-LAST:event_jmiBuscarNombreActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
      
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jmiBuscarRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBuscarRubroActionPerformed
        // Ventan de busqueda de productos por rubro
         escritorio.removeAll();
        escritorio.repaint();
        BusquedaPorRubro bpr = new BusquedaPorRubro();
        bpr.setVisible(true);
        escritorio.add(bpr);
        escritorio.moveToFront(bpr);
    }//GEN-LAST:event_jmiBuscarRubroActionPerformed

    private void jmiBuscarPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBuscarPrecioActionPerformed
        // TVentana de busqueda de productos por precio
        escritorio.removeAll();
        escritorio.repaint();
        BusquedaPorPrecio bpp = new BusquedaPorPrecio();
        bpp.setVisible(true);
        escritorio.add(bpp);
        escritorio.moveToFront(bpp);
    }//GEN-LAST:event_jmiBuscarPrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(DeTodoSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(DeTodoSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(DeTodoSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(DeTodoSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeTodoSA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmbConsultas;
    private javax.swing.JMenuItem jmiBuscarNombre;
    private javax.swing.JMenuItem jmiBuscarPrecio;
    private javax.swing.JMenuItem jmiBuscarRubro;
    private javax.swing.JMenuItem jmiGestorProducto;
    // End of variables declaration//GEN-END:variables

private void cargarProductos(){
    /*
    CONSTRUCTOR: código (int), descripción(String), precio(double), stock(int) y rubro(categorias.)
    */
listaProductos.add(new Producto(10, "Soy un producto", 5.5, 5, Categorias.COMESTIBLES));
listaProductos.add(new Producto(12, "Soy otro producto", 7, 10, Categorias.LIMPIEZA));
listaProductos.add(new Producto(13, "a", 100, 10, Categorias.LIMPIEZA));
listaProductos.add(new Producto(11, "b", 50, 10, Categorias.LIMPIEZA));
}


}
