/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio4;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class GestorDeProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestorDeProducto
     */
    public GestorDeProducto() {
        initComponents();
        cargarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtTitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbGestAgregar = new javax.swing.JButton();
        jbGestEditar = new javax.swing.JButton();
        jbGestEliminar = new javax.swing.JButton();
        jbGestSalir = new javax.swing.JButton();
        jtGestCodigo = new javax.swing.JTextField();
        jtGestDescripcion = new javax.swing.JTextField();
        jtGestPrecio = new javax.swing.JTextField();
        jtGestStock = new javax.swing.JTextField();
        jbGestBuscar = new javax.swing.JButton();
        jcGestCategoria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Gestor de productos");

        jtTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jtTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jtTitle.setText("Gestion de productos");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Descripcion:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Precio:       $");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Categoria:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Stock:");

        jbGestAgregar.setText("Nuevo");
        jbGestAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGestAgregarActionPerformed(evt);
            }
        });

        jbGestEditar.setText("Guardar");
        jbGestEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGestEditarActionPerformed(evt);
            }
        });

        jbGestEliminar.setText("Eliminar");
        jbGestEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGestEliminarActionPerformed(evt);
            }
        });

        jbGestSalir.setText("Salir");
        jbGestSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbGestSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGestSalirActionPerformed(evt);
            }
        });

        jbGestBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/lupa.png"))); // NOI18N
        jbGestBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbGestBuscar.setContentAreaFilled(false);
        jbGestBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbGestBuscar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jbGestBuscar.setMaximumSize(new java.awt.Dimension(20, 20));
        jbGestBuscar.setMinimumSize(new java.awt.Dimension(20, 20));
        jbGestBuscar.setPreferredSize(new java.awt.Dimension(25, 20));
        jbGestBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGestBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar producto por codigo");

        jLabel7.setText("Detalles");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jbGestAgregar)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtGestDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtGestStock, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jbGestEditar)
                                            .addComponent(jtGestPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jbGestEliminar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jbGestSalir))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jcGestCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(213, 213, 213)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jtGestCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)))
                        .addComponent(jbGestBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtGestCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(jbGestBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtGestDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcGestCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jtGestPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jtGestStock, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGestAgregar)
                    .addComponent(jbGestEditar)
                    .addComponent(jbGestEliminar)
                    .addComponent(jbGestSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     // Boton agregar producto
    private void jbGestAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGestAgregarActionPerformed

        String text = "Esta seguro que desea agregar el producto: " + jtGestDescripcion.getText();
        int option = JOptionPane.showConfirmDialog(null, text, "Confirmar agregar?", JOptionPane.YES_NO_OPTION);
        
        if (option == JOptionPane.YES_OPTION) {
            nuevoProducto(); 
        } 
    }//GEN-LAST:event_jbGestAgregarActionPerformed

     //Boton busqueda
    private void jbGestBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGestBuscarActionPerformed
       boolean esta = false;
        
        try
        {
            for(Producto prod : DeTodoSA.listaProductos){
            
            if(prod.getCodigo() == Integer.parseInt(jtGestCodigo.getText())){
                esta= true;
                
                jtGestDescripcion.setText(prod.getDescripcion());
                jtGestPrecio.setText(prod.getPrecio()+ "");
                jtGestStock.setText(prod.getStock()+"");
                jcGestCategoria.setSelectedItem(prod.getRubro());
                return;
        }
            }
        } catch(NumberFormatException err){
        JOptionPane.showMessageDialog(null, "Solo caracteres numericos");
        //La validacion siguiente es para que no tire el mensaje de que no se encuentra el producto
        esta=true;
        }
        
        if(!esta){
        JOptionPane.showMessageDialog(null, "No se encuentra el producto");
         jtGestDescripcion.setText("");
         jtGestPrecio.setText("");
         jtGestStock.setText("");
        }
    }//GEN-LAST:event_jbGestBuscarActionPerformed

    // Boton salir
    private void jbGestSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGestSalirActionPerformed
         dispose();
    }//GEN-LAST:event_jbGestSalirActionPerformed

     // Boton editar
    private void jbGestEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGestEditarActionPerformed
       
        String text = "Esta seguro que desea editar el producto: " + jtGestDescripcion.getText();
        int option = JOptionPane.showConfirmDialog(null, text, "Confirmar editar?", JOptionPane.YES_NO_OPTION);
        
        if (option == JOptionPane.YES_OPTION) {
            editProducto();
        }  
    }//GEN-LAST:event_jbGestEditarActionPerformed

    // Boton eliminar
    private void jbGestEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGestEliminarActionPerformed
        
        String text = "Esta seguro que desea eliminar el producto: " + jtGestDescripcion.getText();
        int option = JOptionPane.showConfirmDialog(null, text, "Confirmar eliminar?", JOptionPane.YES_NO_OPTION);
        
        if (option == JOptionPane.YES_OPTION) {
            deleteProducto();
        }  
    }//GEN-LAST:event_jbGestEliminarActionPerformed
      
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbGestAgregar;
    private javax.swing.JButton jbGestBuscar;
    private javax.swing.JButton jbGestEditar;
    private javax.swing.JButton jbGestEliminar;
    private javax.swing.JButton jbGestSalir;
    private javax.swing.JComboBox<Categorias> jcGestCategoria;
    private javax.swing.JTextField jtGestCodigo;
    private javax.swing.JTextField jtGestDescripcion;
    private javax.swing.JTextField jtGestPrecio;
    private javax.swing.JTextField jtGestStock;
    private javax.swing.JLabel jtTitle;
    // End of variables declaration//GEN-END:variables

private void cargarCombo(){
 jcGestCategoria.removeAllItems();
    
    
    for(Categorias cat : Categorias.values()){
        jcGestCategoria.addItem(cat);
    }
}

private void nuevoProducto(){
   try {
    
     // Creo las variables que extraen los datos de mis jtGest...
    int cod = DeTodoSA.listaProductos.last().getCodigo() + 1;
    String desc = jtGestDescripcion.getText();
    double price = Double.parseDouble(jtGestPrecio.getText());
    int stock = Integer.parseInt(jtGestStock.getText());
    Categorias rubro =  (Categorias)  jcGestCategoria.getSelectedItem();
    
    
    // Constructor de Producto - int codigo, String descripcion, double precio, int stock, Categorias rubro
    Producto addProduct = new Producto(cod, desc, price, stock, rubro);
    
    //Agrego el producto a mi lista de productos
    DeTodoSA.listaProductos.add(addProduct);
    
    //Doy un mensaje de producto creado
    JOptionPane.showMessageDialog(null, "Se ha creado un producto con exito");
    
   }
   catch(NumberFormatException e){
       jtGestDescripcion.setText("");
       jtGestPrecio.setText("");
       jtGestStock.setText("");
       jtGestCodigo.setText("");
       JOptionPane.showMessageDialog(null, "Hubo un error en el ingreso de datos. Por favor, intente nuevamente");
   }
}

private void editProducto(){
     try {
    
     // Creo las variables que extraen los datos de mis jtGest...
    int cod = Integer.parseInt(jtGestCodigo.getText());
    String desc = jtGestDescripcion.getText();
    double price = Double.parseDouble(jtGestPrecio.getText());
    int stock = Integer.parseInt(jtGestStock.getText());
    Categorias rubro =  (Categorias)  jcGestCategoria.getSelectedItem();
    
    //Hay que eliminar el Producto para volver a instanciarlo nuevamente editado
    
    Producto productDestroy = null;
    //Lo buscamos por codigo
    for(Producto prod : DeTodoSA.listaProductos){
        if(cod == prod.getCodigo()){
            productDestroy = prod;
            break;
        }
    }
    
    if(productDestroy != null){
        //Elimino el producto
       DeTodoSA.listaProductos.remove(productDestroy);
        
     // Constructor de Producto - int codigo, String descripcion, double precio, int stock, Categorias rubro
    Producto addProduct = new Producto(cod, desc, price, stock, rubro);
    
    //Agrego el producto a mi lista de productos
    DeTodoSA.listaProductos.add(addProduct);
    
    //Doy un mensaje de producto creado
    JOptionPane.showMessageDialog(null, "Se ha editado un producto con exito");
    }
    
    
  
    
   }
   catch(NumberFormatException e){
       jtGestDescripcion.setText("");
       jtGestPrecio.setText("");
       jtGestStock.setText("");
       jtGestCodigo.setText("");
       JOptionPane.showMessageDialog(null, "Hubo un error en el ingreso de datos. Por favor, intente nuevamente");
   }
    
}

private void deleteProducto(){
      try {
    
     // Creo las variables que extraen los datos de mis jtGest...
    int cod = Integer.parseInt(jtGestCodigo.getText());

    
    //Primero tengo que eliminar el Producto para volver a instanciarlo nuevamente editado
    
    Producto productDestroy = null;
    
    for(Producto prod : DeTodoSA.listaProductos){
        if(cod == prod.getCodigo()){
            productDestroy = prod;
            break;
        }
    }
    
    if(productDestroy != null){
        DeTodoSA.listaProductos.remove(productDestroy);

    //Doy un mensaje de producto eliminado
    JOptionPane.showMessageDialog(null, "Se ha eliminado un producto con exito");
    }
    
      jtGestDescripcion.setText("");
       jtGestPrecio.setText("");
       jtGestStock.setText("");
       jtGestCodigo.setText("");
  
    
   }
   catch(NumberFormatException e){
       jtGestDescripcion.setText("");
       jtGestPrecio.setText("");
       jtGestStock.setText("");
       jtGestCodigo.setText("");
       JOptionPane.showMessageDialog(null, "Hubo un error en el ingreso de datos. Por favor, intente nuevamente");
   }
    
}

}
